apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: 5454
      targetPort: 5454
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: bd-users
          image: postgres:16.0
          ports:
            - containerPort: 5454
          env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: postgres123
      volumes:
        - name: users-data
          persistentVolumeClaim:
            claimName: users-pvc
