apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      containers:
        - name: auth
          image: luispedro189/authentication-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9898
---

apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
spec:
  type: LoadBalancer
  ports:
    - port: 8084 #porta a que dá expose da aplicação (para fora)
      targetPort: 9898 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: auth
