apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app.kubernetes.io/name: products
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: products
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: products
    spec:
      containers:
        - name: products
          image: luispedro189/products-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091

---

apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app.kubernetes.io/name: products
spec:
  type: LoadBalancer
  ports:
    - port: 8084 #porta a que dá expose da aplicação (para fora)
      targetPort: 8091 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: products
