apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app.kubernetes.io/name: user
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: user
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user
    spec:
      containers:
        - name: user
          image: luispedro189/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7777
---

apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app.kubernetes.io/name: user
spec:
  type: LoadBalancer
  ports:
    - port: 8083 #porta a que dá expose da aplicação (para fora)
      targetPort: 7777 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: user
