#deployment-driver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: luispedro189/wallet-service:latest
          ports:
            - containerPort: 9898
          env:
            - name: EUREKA_SERVER
              value: eureka-server
            - name: USER-SERVICE
              value: user-service
            - name: AUTH_DB
              value: wallets
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet-service
  ports:
    - name: http
      port: 8094
      targetPort: 8094
  type: ClusterIP
