apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shipping
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shipping
    spec:
      containers:
        - name: shipping
          image: luispedro189/shipping-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096

---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
spec:
  type: LoadBalancer
  ports:
    - port: 7783 #porta a que dá expose da aplicação (para fora)
      targetPort: 8096 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: shipping
