apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    app.kubernetes.io/name: eureka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eureka
    spec:
      containers:
        - name: eureka
          image: luispedro189/eureka-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app.kubernetes.io/name: eureka
spec:
  type: LoadBalancer
  ports:
    - port: 8082 #porta a que dá expose da aplicação (para fora)
      targetPort: 8761 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte de cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: eureka
