#deployment-driver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: luispedro189/payment-service:latest
          ports:
            - containerPort: 8095
          env:
            - name: EUREKA_SERVER
              value: eureka-server
            - name: USER-SERVICE
              value: user-service
            - name: ORDERS-SERVICE
              value: orders-service
            - name: WALLET-SERVICE
              value: wallet-service
            - name: SHIPPING-SERVICE
              value: shipping-service
            - name: AUTH_DB
              value: payments
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8095
      targetPort: 8095
  type: LoadBalancer
