#deployment-driver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: luispedro189/user-service:latest
          ports:
            - containerPort: 7777
          env:
            - name: EUREKA_SERVER
              value: eureka-server
            - name: USER_DB
              value: bd-users
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 7777
      targetPort: 7777
  type: ClusterIP
