apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
    spec:
      containers:
        - name: orders
          image: luispedro189/orders-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7781

---

apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
spec:
  type: LoadBalancer
  ports:
    - port: 8092 #porta a que dá expose da aplicação (para fora)
      targetPort: 7781 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: orders
