apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app.kubernetes.io/name: reviews
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reviews
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reviews
    spec:
      containers:
        - name: reviews
          image: luispedro189/reviews-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8093

---

apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app.kubernetes.io/name: reviews
spec:
  type: LoadBalancer
  ports:
    - port: 8026 #porta a que dá expose da aplicação (para fora)
      targetPort: 8093 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: reviews
