apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app.kubernetes.io/name: email
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: email
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: email
    spec:
      containers:
        - name: email
          image: luispedro189/email-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8094

---

apiVersion: v1
kind: Service
metadata:
  name: email
  labels:
    app.kubernetes.io/name: email
spec:
  type: LoadBalancer
  ports:
    - port: 7780 #porta a que dá expose da aplicação (para fora)
      targetPort: 8094 #faz bonding com a porta do container (tem de ser a mesma)
  selector: #match com a parte c cima da linha 8 (labels para saber que pertence ao mesmo)
    app.kubernetes.io/name: email
