# deployment-gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      containers:
        - name: spring-cloud-gateway
          image: luispedro189/api-gateway-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_SERVER
              value: eureka-server


---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway
spec:
  selector:
    app: spring-cloud-gateway
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30100
  type: NodePort
