apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: bd-users
spec:
  selector:
    app: bd-users
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bd-users
  template:
    metadata:
      labels:
        app: bd-users
    spec:
      containers:
        - name: bd-users
          image: postgres:16.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: postgres123
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: user-pvc
