#deployment-driver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
        - name: reviews-service
          image: luispedro189/reviews-service:latest
          ports:
            - containerPort: 8093
          env:
            - name: EUREKA_SERVER
              value: eureka-server
            - name: USER-SERVICE
              value: user-service
            - name: ORDERS-SERVICE
              value: orders-service
            - name: SHIPPING-SERVICE
              value: shipping-service
            - name: AUTH_DB
              value: payments
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app: reviews-service
  ports:
    - name: http
      port: 8093
      targetPort: 8093
  type: ClusterIP
